# Usa una imagen oficial con Python
FROM python:3.9

# Instala dependencias
RUN apt-get update && apt-get install -y ffmpeg

# Instala spotdl y yt-dlp
RUN pip install --no-cache-dir spotdl yt-dlp

# Instala Node.js y dependencias
RUN apt-get install -y curl && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs
WORKDIR /app
COPY package*.json ./
RUN npm install

# Copia todos los archivos al contenedor
COPY . .

# Expone el puerto (Render lo detecta)
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "server.js"]
