# Usa una imagen oficial con Python
FROM python:3.9

RUN apt-get update && apt-get install -y openvpn wget
RUN wget https://protonvpn.com/download/ProtonVPN_servers.ovpn
RUN wget https://protonvpn.com/download/XXXX.ovpn
ENV PROTONVPN_USER gonza.layno@gmail.com
ENV PROTONVPN_PASSWORD N2U8y2y2
CMD openvpn --config ProtonVPN_servers.ovpn --auth-user-pass <(echo "$PROTONVPN_USER\n$PROTONVPN_PASSWORD")
# Instala dependencias
RUN apt-get update && apt-get install -y ffmpeg

# Instala spotdl y yt-dlp
RUN pip install --no-cache-dir spotdl yt-dlp

# Instala Node.js y dependencias
RUN apt-get install -y curl && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs
WORKDIR /app
COPY package*.json ./
RUN npm install

# Copia todos los archivos al contenedor
COPY . .

# Expone el puerto (Render lo detecta)
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "server.js"]
