services:
  - name: spotdl-app
    type: web
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install spotdl
      npm install
    startCommand: node server.js
